server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: app
          uri: http://localhost:8081
          predicates:
            - Path=/주문/**, /orderInfos/**, /메뉴판/**, /통합주문상태/**, /menuInfos/**, /orderStatuses/**
        - id: pay
          uri: http://localhost:8082
          predicates:
            - Path=/결제이력/**, /paymentInfos/**, 
        - id: store
          uri: http://localhost:8083
          predicates:
            - Path=/주문관리/**, /orderManagements/**, /주문상세보기/**, /orderDetails/**
        - id: customer
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: rider
          uri: http://localhost:8085
          predicates:
            - Path=/deliveryInfos/**, /deliveries/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: app
          uri: http://app:8080
          predicates:
            - Path=/주문/**, /orderInfos/**, /메뉴판/**, /통합주문상태/**, /menuInfos/**, /orderStatuses/**
        - id: pay
          uri: http://pay:8080
          predicates:
            - Path=/결제이력/**, /paymentInfos/**, 
        - id: store
          uri: http://store:8080
          predicates:
            - Path=/주문관리/**, /orderManagements/**, /주문상세보기/**, /orderDetails/**
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=, 
        - id: rider
          uri: http://rider:8080
          predicates:
            - Path=/deliveryInfos/**, /deliveries/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
